---

cron-croninfo:
  path: /info
  defaults: {
    _controller: 'SimpleSAML\Module\cron\Controller\Cron::info'
  }
  methods: [GET]

cron-run:
  path: /run/{tag}/{key}/{output}
  defaults: {
    _controller: 'SimpleSAML\Module\cron\Controller\Cron::run',
    output: 'silent'
  }
  methods: [GET]
#  TODO: Use this instead of controller-code when Symfony 6.1 is available
#  condition:  "params['key'] not in ['secret', 'RANDOM_KEY']"
