core-login:
    path:       /login/{as}
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\LoginController:login', as: null }
core-account:
    path:       /account/{as}
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\LoginController:account' }
core-logout:
    path:       /logout/{as}
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\LoginController:logout' }
core-error-nocookie:
    path:       /error/nocookie
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\ExceptionController:nocookie' }
core-cardinality:
    path:       /error/cardinality
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\ExceptionController:cardinality' }
core-warning-shortssointerval:
    path:       /warning/short_sso_interval
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\ExceptionController:shortSsoInterval' }
core-post-redirect:
    path:       /postredirect
    defaults:   { _controller: 'SimpleSAML\Module\core\Controller\RedirectionController:postredirect' }
