admin-main:
    path:       /
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::main' }
admin-diagnostics:
    path:       /diagnostics
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::diagnostics' }
admin-phpinfo:
    path:       /phpinfo
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::phpinfo' }
admin-test:
    path:       /test/{as}
    defaults:   { _controller: 'SimpleSAML\Module\admin\TestController::main', as: null }
admin-fed:
    path:       /federation
    defaults:   { _controller: 'SimpleSAML\Module\admin\FederationController::main' }
