admin-main:
    path:       /
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::main' }
admin-diagnostics:
    path:       /diagnostics
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::diagnostics' }
admin-phpinfo:
    path:       /phpinfo
    defaults:   { _controller: 'SimpleSAML\Module\admin\ConfigController::phpinfo' }
admin-test:
    path:       /test/{as}
    defaults:   { _controller: 'SimpleSAML\Module\admin\TestController::main', as: null }
admin-fed:
    path:       /federation
    defaults:   { _controller: 'SimpleSAML\Module\admin\FederationController::main' }
admin-fed-cert:
    path:       /federation/cert
    defaults:   { _controller: 'SimpleSAML\Module\admin\FederationController::downloadCert' }
admin-fed-show:
    path:       /federation/show
    defaults:   { _controller: 'SimpleSAML\Module\admin\FederationController::showRemoteEntity' }
admin-fed-converter:
    path:       /federation/metadata-converter
    defaults:   { _controller: 'SimpleSAML\Module\admin\FederationController::metadataConverter' }
